name: Repo Sync and Build
on:
  schedule:
  - cron: '55 10 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync Fork
      uses: TG908/fork-sync@v1.1
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        owner: g4klx
        base: master
        head: master
    - uses: actions/checkout@master
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.11
      with:
        name: neilbartley/ysfreflector
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: YSFReflector/docker
        snapshot: true
