name: Repo Sync
on:
  schedule:
  - cron: "0 1 * * *"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "g4klx/YSFClients"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.GH_TOKEN }}
